### ISSUE TITLE
Console output is printed on the same line

### ISSUE THREAD

**Issue by ghost** [ITGlobal/CLI#30]
Auto generated help for commands is printed on the same line.
It seems that only Carriage Returns (CR) are emitted without Line Feeds (LF).
Or is it Live Text accidentally switched on ?

**Comment by kapitanov** [comment]
Could you provide some details? Your OS, a screenshot,, a code sample to reproduce this bug?

**Comment by ghost** [comment]
[ConsoleApp1.zip](https://github.com/ITGlobal/CLI/files/4270639/ConsoleApp1.zip)

Correct output (with ITGlobal.CLI v3.0.25):
```
parser.HelpText

USAGE
   ConsoleApp1.netcoreapp3.1 [OPTIONS] COMMAND

OPTIONS
   --json Emit JSON response
   --help Print help and exit

COMMANDS
   version Get version

```
Wrong output (with ITGlobal.CLI v3.1.7):
```
parser.HelpText
   version Get versionnd exit[OPTIONS] COMMAND
```

**Comment by kapitanov** [comment]
Please try [`v3.1.8`](https://www.nuget.org/packages/ITGlobal.CLI/3.1.8). I hope it fixes this error.

**Comment by ghost** [comment]
Yes!
Thank you.
